name: CI

on: [push, pull_request]

jobs:
  checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv add --group dev black mypy ruff
      - name: Ruff Lint
        run: uvx ruff check
      - name: Black Format Check
        run: uvx black .
      - name: Mypy Type Check
        run: uvx mypy .

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: checks
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest with Coverage
        run: python -m pytest --cov=weather_mcp --cov=client --cov-report=term tests/
